name: clean_arc_flutter
description: Clean Architecture Uptodate

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  progress_dialog: ^1.2.4
  event_bus: ^1.1.1
  shared_preferences: ^0.5.8
  dio_http_cache: ^0.2.8
  connectivity: ^0.4.9
  rxdart: ^0.24.1
  permission_handler: ^5.0.1+1
  injector: ^1.0.8
  dio: ^3.0.9
  provider: ^4.3.1
  logging: ^0.11.4
  flutter_clean_architecture: 3.1.0
  flutter_dotenv: ^2.1.0
  rxdart_codemod: ^0.1.5
  cupertino_icons: ^0.1.2
  encrypt: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  gen_lang: 0.1.3

flutter:
  uses-material-design: true
  assets:
   - lib/app/ui/assets/images/
   - lib/app/ui/assets/icons/
   - lib/app/ui/assets/misc/
   - .env
